application: rolodxcdn
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles

- url: /images
  static_dir: images
  
- url: /scripts
  static_dir: scripts
  
- url: /.*
  static_files: index.html
  upload: index.html